<a href="https://colab.research.google.com/github/darshil8008/ML-Algorithms-Implementation/blob/main/DecisionTreeClassifier_on_drug200_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Loading dataset

df = pd.read_csv(r'C:\Users\hp\Downloads\drug200.csv')

In [ ]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
df.shape

(200, 6)

In [ ]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [ ]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [ ]:
y = df["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

In [ ]:
X_trainset.shape

(140, 5)

In [ ]:
y_trainset.shape

(140,)

In [ ]:
X_testset.shape

(60, 5)

In [ ]:
y_testset.shape

(60,)

In [ ]:
# Creating the model

clf = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
clf 

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
clf.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
# Prediction

ypred = clf.predict(X_testset)

In [ ]:
ypred [0:5]

array(['drugY', 'drugX', 'drugX', 'drugX', 'drugX'], dtype=object)

In [ ]:
y_testset [0:5]

40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
Name: Drug, dtype: object

In [ ]:
# Accuracy evaluation

from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, ypred))

DecisionTrees's Accuracy:  0.9833333333333333


In [ ]:
dp=pd.DataFrame({'Actual':y_testset,'Predicted':ypred})
dp

Actual Predicted
40   drugY     drugY
51   drugX     drugX
139  drugX     drugX
197  drugX     drugX
170  drugX     drugX
82   drugC     drugC
183  drugY     drugY
46   drugA     drugA
70   drugB     drugB
100  drugA     drugA
179  drugY     drugY
83   drugA     drugA
25   drugY     drugY
190  drugY     drugY
159  drugX     drugX
173  drugY     drugY
95   drugX     drugX
3    drugX     drugX
41   drugB     drugB
58   drugX     drugX
14   drugX     drugX
143  drugY     drugY
12   drugY     drugY
6    drugY     drugY
182  drugX     drugX
161  drugB     drugB
128  drugY     drugY
122  drugY     drugY
101  drugA     drugA
86   drugX     drugX
64   drugB     drugB
47   drugC     drugC
158  drugC     drugC
34   drugX     drugX
38   drugX     drugX
196  drugC     drugC
4    drugY     drugY
72   drugX     drugX
67   drugX     drugX
145  drugX     drugX
156  drugA     drugA
115  drugY     drugY
155  drugC     drugC
15   drugY     drugY
61   drugA     drugA
175  drugY     drugY
120  drugY     drugY
130  drugY     drugY
23   drugY     drugY
153  drugX     drugY
31   drugB     drugB
103  drugX     drugX
89   drugY     drugY
132  drugX     drugX
109  drugY     drugY
126  drugY     drugY
17   drugA     drugA
30   drugX     drugX
178  drugY     drugY
162  drugX     drugX

In [ ]:
print(metrics.classification_report(y_testset,ypred))
print(metrics.confusion_matrix(y_testset,ypred))
print(metrics.accuracy_score(y_testset,ypred))

             precision    recall  f1-score   support

      drugA       1.00      1.00      1.00         7
      drugB       1.00      1.00      1.00         5
      drugC       1.00      1.00      1.00         5
      drugX       1.00      0.95      0.98        21
      drugY       0.96      1.00      0.98        22

avg / total       0.98      0.98      0.98        60

[[ 7  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 20  1]
 [ 0  0  0  0 22]]
0.9833333333333333
