<a href="https://colab.research.google.com/github/darshil8008/ML-Algorithms-Implementation/blob/main/DecisionTreeClassifier_on_balance_scaling_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Loading dataset

df = pd.read_csv(r'C:\Users\hp\Downloads\balance-scale.csv')

In [ ]:
df

Class  L-Weight  L-Distance  R-Weight  R-Distance
0       B         1           1         1           1
1       R         1           1         1           2
2       R         1           1         1           3
3       R         1           1         1           4
4       R         1           1         1           5
..    ...       ...         ...       ...         ...
620     L         5           5         5           1
621     L         5           5         5           2
622     L         5           5         5           3
623     L         5           5         5           4
624     B         5           5         5           5

[625 rows x 5 columns]

In [ ]:
df.shape

(625, 5)

In [ ]:
# Preparing the Data

X = df.iloc[1:625,1:4].values
y = df.iloc[1:625,4].values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Class       625 non-null    object
 1   L-Weight    625 non-null    int64 
 2   L-Distance  625 non-null    int64 
 3   R-Weight    625 non-null    int64 
 4   R-Distance  625 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In [ ]:
df.describe()

L-Weight  L-Distance    R-Weight  R-Distance
count  625.000000  625.000000  625.000000  625.000000
mean     3.000000    3.000000    3.000000    3.000000
std      1.415346    1.415346    1.415346    1.415346
min      1.000000    1.000000    1.000000    1.000000
25%      2.000000    2.000000    2.000000    2.000000
50%      3.000000    3.000000    3.000000    3.000000
75%      4.000000    4.000000    4.000000    4.000000
max      5.000000    5.000000    5.000000    5.000000

In [ ]:
# Splitting the data into Train and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
# Training and Making Predictions

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
# Evaluating the Algorithm

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0 28  4  0  0]
 [17  0  4  0  0]
 [18  5  0  0  0]
 [18  3  2  0  0]
 [20  5  1  0  0]]
             precision    recall  f1-score   support

          1       0.00      0.00      0.00        32
          2       0.00      0.00      0.00        21
          3       0.00      0.00      0.00        23
          4       0.00      0.00      0.00        23
          5       0.00      0.00      0.00        26

avg / total       0.00      0.00      0.00       125

